# Site settings
author: Umar Khan
title: Khan's Eye View
header-img: img/home-bg.png
email: umarkhan314@outlook.com
copyright_name: Umar Khan
description: > # this means to ignore newlines until "baseurl:"
  Observations. Thoughts. Ideas. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  thekhan314

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
